package epsi.model;

// Generated 6 mai 2015 11:18:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommandeContient generated by hbm2java
 */
@Entity
@Table(name = "commande_contient", catalog = "bdd_lpdc")
public class CommandeContient implements java.io.Serializable {

	private CommandeContientId id;
	private Produit produit;
	private Commande commande;
	private int nombreProduit;

	public CommandeContient() {
	}

	public CommandeContient(CommandeContientId id, Produit produit,
			Commande commande, int nombreProduit) {
		this.id = id;
		this.produit = produit;
		this.commande = commande;
		this.nombreProduit = nombreProduit;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCommande", column = @Column(name = "id_Commande", nullable = false)),
			@AttributeOverride(name = "idProduit", column = @Column(name = "id_Produit", nullable = false)) })
	public CommandeContientId getId() {
		return this.id;
	}

	public void setId(CommandeContientId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Produit", nullable = false, insertable = false, updatable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Commande", nullable = false, insertable = false, updatable = false)
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@Column(name = "nombre_produit", nullable = false)
	public int getNombreProduit() {
		return this.nombreProduit;
	}

	public void setNombreProduit(int nombreProduit) {
		this.nombreProduit = nombreProduit;
	}

}
