package epsi.model;

// Generated 6 mai 2015 11:18:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtatCommande generated by hbm2java
 */
@Entity
@Table(name = "etat_commande", catalog = "bdd_lpdc")
public class EtatCommande implements java.io.Serializable {

	private Integer idEtat;
	private String libelleEtat;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public EtatCommande() {
	}

	public EtatCommande(String libelleEtat) {
		this.libelleEtat = libelleEtat;
	}

	public EtatCommande(String libelleEtat, Set<Commande> commandes) {
		this.libelleEtat = libelleEtat;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Etat", unique = true, nullable = false)
	public Integer getIdEtat() {
		return this.idEtat;
	}

	public void setIdEtat(Integer idEtat) {
		this.idEtat = idEtat;
	}

	@Column(name = "libelle_Etat", nullable = false, length = 100)
	public String getLibelleEtat() {
		return this.libelleEtat;
	}

	public void setLibelleEtat(String libelleEtat) {
		this.libelleEtat = libelleEtat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCommande")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
