package epsi.model;

// Generated 6 mai 2015 11:18:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "bdd_lpdc")
public class Menu implements java.io.Serializable {

	private long idProduit;
	private Produit produit;
	private int nbPersonne;
	private Float prix;
	private String designation;
	private String description;

	public Menu() {
	}

	public Menu(Produit produit, int nbPersonne) {
		this.produit = produit;
		this.nbPersonne = nbPersonne;
	}

	public Menu(Produit produit, int nbPersonne, Float prix,
			String designation, String description) {
		this.produit = produit;
		this.nbPersonne = nbPersonne;
		this.prix = prix;
		this.designation = designation;
		this.description = description;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "produit"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_Produit", unique = true, nullable = false)
	public long getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(long idProduit) {
		this.idProduit = idProduit;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "nb_personne", nullable = false)
	public int getNbPersonne() {
		return this.nbPersonne;
	}

	public void setNbPersonne(int nbPersonne) {
		this.nbPersonne = nbPersonne;
	}

	@Column(name = "prix", precision = 12, scale = 0)
	public Float getPrix() {
		return this.prix;
	}

	public void setPrix(Float prix) {
		this.prix = prix;
	}

	@Column(name = "designation", length = 50)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
