package epsi.model;

// Generated 6 mai 2015 11:18:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Panier generated by hbm2java
 */
@Entity
@Table(name = "panier", catalog = "bdd_lpdc")
public class Panier implements java.io.Serializable {

	private Integer idPanier;
	private User user;
	private Date dateTime;
	private Set<PanierContient> panierContients = new HashSet<PanierContient>(0);

	public Panier() {
	}

	public Panier(User user, Date dateTime) {
		this.user = user;
		this.dateTime = dateTime;
	}

	public Panier(User user, Date dateTime, Set<PanierContient> panierContients) {
		this.user = user;
		this.dateTime = dateTime;
		this.panierContients = panierContients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Panier", unique = true, nullable = false)
	public Integer getIdPanier() {
		return this.idPanier;
	}

	public void setIdPanier(Integer idPanier) {
		this.idPanier = idPanier;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_User", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateTime", nullable = true, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "panier")
	public Set<PanierContient> getPanierContients() {
		return this.panierContients;
	}

	public void setPanierContients(Set<PanierContient> panierContients) {
		this.panierContients = panierContients;
	}

}
