package epsi.model;

// Generated 6 mai 2015 11:18:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PanierContientId generated by hbm2java
 */
@Embeddable
public class PanierContientId implements java.io.Serializable {

	private int idPanier;
	private int idProduits;

	public PanierContientId() {
	}

	public PanierContientId(int idPanier, int idProduits) {
		this.idPanier = idPanier;
		this.idProduits = idProduits;
	}

	@Column(name = "id_Panier", nullable = false)
	public int getIdPanier() {
		return this.idPanier;
	}

	public void setIdPanier(int idPanier) {
		this.idPanier = idPanier;
	}

	@Column(name = "id_Produits", nullable = false)
	public int getIdProduits() {
		return this.idProduits;
	}

	public void setIdProduits(int idProduits) {
		this.idProduits = idProduits;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PanierContientId))
			return false;
		PanierContientId castOther = (PanierContientId) other;

		return (this.getIdPanier() == castOther.getIdPanier())
				&& (this.getIdProduits() == castOther.getIdProduits());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPanier();
		result = 37 * result + this.getIdProduits();
		return result;
	}

}
