package epsi.model;

// Generated 6 mai 2015 11:18:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PanierContient generated by hbm2java
 */
@Entity
@Table(name = "panier_contient", catalog = "bdd_lpdc")
public class PanierContient implements java.io.Serializable {

	private PanierContientId id;
	private Produit produit;
	private Panier panier;
	private int nombreProduit;

	public PanierContient() {
	}

	public PanierContient(PanierContientId id, Produit produit, Panier panier,
			int nombreProduit) {
		this.id = id;
		this.produit = produit;
		this.panier = panier;
		this.nombreProduit = nombreProduit;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPanier", column = @Column(name = "id_Panier", nullable = false)),
			@AttributeOverride(name = "idProduits", column = @Column(name = "id_Produits", nullable = false)) })
	public PanierContientId getId() {
		return this.id;
	}

	public void setId(PanierContientId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_Produits", nullable = false, insertable = false, updatable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_Panier", nullable = false, insertable = false, updatable = false)
	public Panier getPanier() {
		return this.panier;
	}

	public void setPanier(Panier panier) {
		this.panier = panier;
	}

	@Column(name = "nombre_produit", nullable = false)
	public int getNombreProduit() {
		return this.nombreProduit;
	}

	public void setNombreProduit(int nombreProduit) {
		this.nombreProduit = nombreProduit;
	}

}
