package epsi.model;

// Generated 6 mai 2015 11:18:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * TypeContenant generated by hbm2java
 */
@Entity
@Table(name = "type_contenant", catalog = "bdd_lpdc")
public class TypeContenant implements java.io.Serializable {

	private Integer idTypeContenant;
	private String designationTypeContenant;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public TypeContenant() {
	}

	public TypeContenant(String designationTypeContenant) {
		this.designationTypeContenant = designationTypeContenant;
	}

	public TypeContenant(String designationTypeContenant, Set<Produit> produits) {
		this.designationTypeContenant = designationTypeContenant;
		this.produits = produits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Type_Contenant", unique = true, nullable = false)
	public Integer getIdTypeContenant() {
		return this.idTypeContenant;
	}

	public void setIdTypeContenant(Integer idTypeContenant) {
		this.idTypeContenant = idTypeContenant;
	}

	@Column(name = "designation_Type_Contenant", nullable = false, length = 100)
	public String getDesignationTypeContenant() {
		return this.designationTypeContenant;
	}

	public void setDesignationTypeContenant(String designationTypeContenant) {
		this.designationTypeContenant = designationTypeContenant;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "typeContenants")
	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
